cabal-version:      2.4
name:               haskell-int-overflow-debug-lab
version:            0.1.0.0
build-type:         Simple

library
  exposed-modules:    Identifier
  hs-source-dirs:     src
  build-depends:      base >=4.14 && <5
  default-language:   Haskell2010

test-suite spec
  type:               exitcode-stdio-1.0
  main-is:            Spec.hs
  hs-source-dirs:     test
  build-depends:
      base >=4.14 && <5,
      haskell-int-overflow-debug-lab,
      hspec >=2.10 && <2.12
  default-language:   Haskell2010
